#!/usr/bin/python

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def solve(first, second, length):
    total = 0
    x = first+second
    if(first%2 == 0):
        total += first
    if(second%2 == 0):
        total += second
    while x < length:
        if(x%2 == 0):
            total += x
        temp = x
        x = x+second
        second = temp
    return total
